name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to 'master' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          cd ~/app-flask-ml
          git pull origin main
          docker stop app || true
          docker rm app || true
          docker build -t app-flask-ml .
          docker run -d -p 5000:5000 --name app app-flask-ml
